Improve -S option parsing and add it to usage

diff --git a/uuniq/inttest b/uuniq/inttest
--- a/uuniq/inttest
+++ b/uuniq/inttest
@@ -225,6 +225,23 @@ TEST=$(echo "$TEST" | sed -E 's/uuniq ([0-9]{4}-[0-9]{2}-[0-9]{2})/uuniq YYYY-MM
 EXPECTED="uuniq YYYY-MM-DD"
 checkeq "$TEST" "$EXPECTED"
 
+echo "uuniq: missing argument: -S"
+TEST=$(./uuniq -S 2>&1)
+checkeq $? 1
+EXPECTED="uuniq: missing argument: -S"
+checkeq "$TEST" "$EXPECTED"
+
+echo "uuniq: invalid argument: -S"
+TEST=$(./uuniq -Sfoo 2>&1)
+checkeq $? 1
+EXPECTED="uuniq: invalid argument: -S: foo"
+checkeq "$TEST" "$EXPECTED"
+
+TEST=$(./uuniq -S bar 2>&1)
+checkeq $? 1
+EXPECTED="uuniq: invalid argument: -S: bar"
+checkeq "$TEST" "$EXPECTED"
+
 echo "uuniq <unknown option>"
 TEST=$(./uuniq -xyz 2>&1)
 checkeq $? 1
